# Generated by Django 3.1.7 on 2021-05-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='src',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
