# Generated by Django 3.1.7 on 2021-03-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default='/', upload_to='media/'),
        ),
    ]
