# Generated by Django 3.1.7 on 2021-04-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210329_0750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
